[package]
name = "coffee_contract"
version = "0.1.0"
edition = "2021"
default-run = "coffee"


[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["library"]
library = []

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[package.metadata.scripts]
optimize = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/optimizer:0.16.0
"""

[dependencies]
cosmwasm-schema = "2.2.0"
cosmwasm-std = { version = "2.2.0", features = ["cosmwasm_1_4"] }
cw-storage-plus = "2.0.0"
cw2 = "2.0.0"
schemars = "0.8.16"
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.58" }

# 👇 explicitly add ed25519-zebra with alloc feature
ed25519-zebra = { git = "https://github.com/ZcashFoundation/ed25519-zebra.git", branch = "main", features = ["alloc"] }

[dev-dependencies]
cw-multi-test = "2.0.0"

[patch.crates-io]
# 👇 force all crates that depend on ed25519-zebra to use the git version
ed25519-zebra = { git = "https://github.com/ZcashFoundation/ed25519-zebra.git", branch = "main" }

[[bin]]
name = "coffee"
path = "src/coffee.rs"